version: "3.8"

services:
  mysql-service:
    container_name: mysql-ministerio
    image: mysql:${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATABASE_PERSISTANT_DIR}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - ${MYSQL_PORT}:3306

  tickets-api-service:
    container_name: tickets-api
    stdin_open: true
    tty: true
    image: ministerio/tickets-api:latest
    command: /start-reload.sh
    environment:
      - TICKETS_API_REPOSITORY_PATH=${TICKETS_API_REPOSITORY_PATH}
      - TICKETS_API_DATABASE_URL=${TICKETS_API_DATABASE_URL}
    volumes:
      - ${TICKETS_API_REPOSITORY_PATH}:/app/tickets-api
    depends_on:
      - mysql-service
    ports:
      - 8000:80

  tickets-admin:
    container_name: tickets-admin
    stdin_open: true
    tty: true
    image: ministerio/tickets-admin:latest
    command: "sh /start-reload.sh"
    environment:
      - VIRTUAL_HOST=${TICKETS_ADMIN_VIRTUAL_HOST}
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ${TICKETS_ADMIN_REPOSITORY_PATH}:/usr/src/tickets-admin
    ports:
      - 3000:5173